imagePullSecret: ghcr-secret

frontend:
  deployment:
    image: ghcr.io/tim-pirotte/frontend:latest
    imagePullPolicy: Always
    containerPort: 8000

  service:
    port: 8000

api:
  deployment:
    image: ghcr.io/tim-pirotte/api:latest
    imagePullPolicy: Always
    containerPort: 5000

  service:
    port: 5000
