imagePullSecret: ghcr-secret

frontend:
  deployment:
    image: ghcr.io/tim-pirotte/frontend:latest
    pullPolicy: Always
    containerPort: 8000

  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 30080

api:
  deployment:
    image: ghcr.io/tim-pirotte/api:latest
    pullPolicy: Always
    containerPort: 5000

  service:

