services:
  api:
    build: ./api
    env_file:
      - ./api/.env
    networks:
      - redis
      - postgres
    ports: 
      - 5000:5000
    secrets:
      - redis_write
      - redis_read_delete
      - postgres_app_default

  frontend:
    build: ./frontend
    ports:
      - 8000:8000

  redis:
    build: ./redis
    restart: always
    networks:
      - redis
    secrets:
      - redis_acl

  postgres:
    build: ./postgres
    env_file:
      - ./postgres/.env
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    secrets:
      - pg_admin

networks:
  redis:
  postgres:

volumes:
  postgres-data:

secrets:
  redis_acl:
    file: ./redis/users.acl
  redis_write:
    file: ./redis/write.secret
  redis_read_delete:
    file: ./redis/read_delete.secret

  pg_admin:
    file: ./postgres/admin.secret
  postgres_app_default:
    file: ./postgres/app_default.secret
