services:
  api:
    build: ./api
    env_file:
      - ./api/.env
    networks:
      - redis
    ports: 
      - 5000:5000
    secrets:
      - redis_write
      - redis_read_delete

  frontend:
    build: ./frontend
    ports:
      - 8000:8000

  redis:
    build: ./redis
    restart: always
    networks:
      - redis
    secrets:
      - redis_acl

  postgres:
    volumes:
      - postgres-data:/var/lib/postgresql

networks:
  redis:

volumes:
  - postgres-data:

secrets:
  redis_acl:
    file: ./redis/users.acl
  redis_write:
    file: ./redis/write.secret
  redis_read_delete:
    file: ./redis/read_delete.secret
