services:
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - 8000:8000

  redis:
    image: dhi.io/redis:8
    restart: always
    command: redis-server --requirepass unsafe
