apiVersion: v1
kind: ConfigMap
metadata:
  name: config-api
data:
  SERIALIZER_VALIDITY_SECONDS: "86400"

  SCRYPT_SALT_BYTES: "32"
  SCRYPT_N_POW_2: "15"
  SCRYPT_R: "8"
  SCRYPT_P: "1"
  SCRYPT_MAX_MEM_MB: "64"
  SCRYPT_DKLEN: "64"

  JWT_ALGORITHM: "HS256"
  JWT_VALIDITY_DAYS: "1"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "rna_folding"
  POSTGRES_POOL_SIZE: "5"
  POSTGRES_MAX_OVERFLOW: "10"

  MIN_PASSWORD_LEN: "8"
  MAX_PASSWORD_LEN: "32"
  MIN_MAIL_LEN: "3"
  MAX_MAIL_LEN: "255"
  MIN_DISPLAY_NAME_LEN: "1"
  MAX_DISPLAY_NAME_LEN: "255"

  SESSION_TTL: "60"
  MIN_SEQ_DISPLAY_NAME_LEN: "1"
  MAX_SEQ_DISPLAY_NAME_LEN: "255"
  MIN_SEQ_LEN: "3"
  MAX_SEQ_LEN: "1024"
  MIN_FOLDS: "1"
  MAX_FOLDS: "9"
  MIN_STEPS: "1"
  MAX_STEPS: "25"
  MAX_PREDICTIONS_SAVED: "100"
