apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.deployment.image }}"
          imagePullPolicy: {{ .Values.frontend.deployment.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.deployment.containerPort }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
