apiVersion: v1
kind: Secret
metadata:
  name: secrets-api
type: Opaque
stringData:
  serializer_secret: "example"
  jwt_secret: "example"
  redis_write: "example"
  redis_read_delete: "example"
  postgres_accounts_s: "example"
  postgres_accounts_su: "example"
  postgres_accounts_siu: "example"
  postgres_accounts_sd: "example"
  postgres_predictions_s: "example"
  postgres_predictions_id: "example"
