apiVersion: v1
kind: Secret
metadata:
  name: secrets-api
type: Opaque
stringData:
  serializer_secret: {{ .Files.Get "files/api/serializer.secret" | quote }}
  jwt_secret: {{ .Files.Get "files/api/jwt.secret" | quote }}
  redis_write: {{ .Files.Get "files/redis/users/write.secret" | quote }}
  redis_read_delete: {{ .Files.Get "files/redis/users/read_delete.secret" | quote }}
  postgres_accounts_s: {{ .Files.Get "files/postgres/users/accounts_s.secret" | quote }}
  postgres_accounts_su: {{ .Files.Get "files/postgres/users/accounts_su.secret" | quote }}
  postgres_accounts_siu: {{ .Files.Get "files/postgres/users/accounts_siu.secret" | quote }}
  postgres_accounts_sd: {{ .Files.Get "files/postgres/users/accounts_sd.secret" | quote }}
  postgres_predictions_s: {{ .Files.Get "files/postgres/users/predictions_s.secret" | quote }}
  postgres_predictions_id: {{ .Files.Get "files/postgres/users/predictions_id.secret" | quote }}
