apiVersion: v1
kind: Secret
metadata:
  name: secrets-postgres
type: Opaque
stringData:
  pg_admin: {{ .Files.Get "files/postgres/users/admin.secret" | quote }}
  postgres_init_sql: {{ .Files.Get "files/postgres/init.sql" | quote }}
