name: Kubernetes Deployment

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Copy secret files
        run: |
          Copy-Item ${{ secrets.JWT }} -Destination chart/files/api/jwt.secret
          Copy-Item ${{ secrets.SERIALIZER }} -Destination chart/files/api/serializer.secret
          Copy-Item ${{ secrets.SQL_INIT }} -Destination chart/files/postgres/init.sql
          Copy-Item ${{ secrets.ADMIN }} -Destination chart/files/postgres/users/admin.secret
          Copy-Item ${{ secrets.ACCOUNTS_S }} -Destination chart/files/postgres/users/accounts_s.secret
          Copy-Item ${{ secrets.ACCOUNTS_SD }} -Destination chart/files/postgres/users/accounts_sd.secret
          Copy-Item ${{ secrets.ACCOUNTS_SIU }} -Destination chart/files/postgres/users/accounts_siu.secret
          Copy-Item ${{ secrets.ACCOUNTS_SU }} -Destination chart/files/postgres/users/accounts_su.secret
          Copy-Item ${{ secrets.PREDICTIONS_S }} -Destination chart/files/postgres/users/predictions_s.secret
          Copy-Item ${{ secrets.PREDICTIONS_ID }} -Destination chart/files/postgres/users/predictions_id.secret
          Copy-Item ${{ secrets.WRITE }} -Destination chart/files/redis/users/write.secret
          Copy-Item ${{ secrets.READ_DELETE }} -Destination chart/files/redis/users/read_delete.secret
          Copy-Item ${{ secrets.ACL }} -Destination chart/files/redis/users.acl

      - name: Deploy
        run: |
          helm upgrade --install fusion-fold ./chart `
            -n fusion-fold `
            --create-namespace `
            --wait `
            --timeout 15m

      - name: Restart deployments
        run: |
            kubectl rollout restart deployment/frontend -n fusion-fold
            kubectl rollout restart deployment/api -n fusion-fold
            kubectl rollout restart deployment/redis -n fusion-fold
            kubectl rollout restart statefulset/postgres -n fusion-fold
